#!/usr/bin/env python3
"""
Generate docs/INTEGRATIONS.md — how to use the library with any agent runtime.

Counts are pulled from manifest.json so the doc never drifts. The integrations
themselves are runtime-agnostic: every skill is plain markdown with a YAML header,
readable by any LLM agent. No deps, no model calls.

Usage:
  python tools/gen_integrations.py            # write the doc
  python tools/gen_integrations.py --check    # exit 1 if stale
"""
import json, os, sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(REPO, "manifest.json")
OUT = os.path.join(REPO, "docs", "INTEGRATIONS.md")

RUNTIMES = [
    ("Any agent",
     "Point your agent at `skills/<category>/<name>/SKILL.md`. It is plain markdown with a "
     "small YAML header — no runtime-specific syntax."),
    ("Terminal / scripts",
     "Use the bundled CLI (stdlib Python, zero deps):\n\n"
     "```\n"
     "python tools/skills_cli.py list --with-scripts\n"
     "python tools/skills_cli.py search latency\n"
     "python tools/skills_cli.py cat promotion-case | your-agent\n"
     "```"),
    ("Claude Code",
     "Add to your `CLAUDE.md`:\n\n```\nskillsDir: skills/\n```"),
    ("GitHub Copilot",
     "Copy the relevant skill folder into `.github/copilot-instructions/`."),
    ("Cursor",
     "Reference a skill inline via `@skills/<name>/SKILL.md`, or add the path to "
     "`.cursorrules`."),
]


def render(data):
    c = data["counts"]
    lines = [
        "# Integrations",
        "",
        "Generated by `tools/gen_integrations.py` from `manifest.json` — do not edit by hand.",
        "",
        f"The library ships **{c['prompts']} prompts** and **{c['skills']} skills** across "
        f"**{c['categories']} categories** ({c['skills_with_scripts']} skills carry a "
        f"validation/calculation script). Everything is plain markdown plus stdlib Python, so "
        f"it runs under any LLM agent — no provider lock-in.",
        "",
        "Machine-readable index: [`manifest.json`](../manifest.json). "
        "Task coverage: [`prompt-skill-map.md`](prompt-skill-map.md).",
        "",
    ]
    for title, body in RUNTIMES:
        lines.append(f"## {title}")
        lines.append("")
        lines.append(body)
        lines.append("")
    return "\n".join(lines)


def main():
    with open(MANIFEST, encoding="utf-8") as f:
        data = json.load(f)
    content = render(data)
    if "--check" in sys.argv:
        current = ""
        if os.path.isfile(OUT):
            with open(OUT, encoding="utf-8") as f:
                current = f.read()
        if current != content:
            print("FAIL: docs/INTEGRATIONS.md is stale — run: python tools/gen_integrations.py")
            sys.exit(1)
        print("PASS: INTEGRATIONS.md up to date")
        sys.exit(0)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Wrote {os.path.relpath(OUT, REPO)}")


if __name__ == "__main__":
    main()
