#!/usr/bin/env python3
"""
Generate docs/prompt-skill-map.md — which tasks exist as a prompt, a skill, or both.

Reads manifest.json (run tools/gen_manifest.py first) and matches prompts to skills by
normalised name. No deps, no LLM.

Usage:
  python tools/gen_crossmap.py            # write the doc
  python tools/gen_crossmap.py --check    # exit 1 if the doc is stale
"""
import json, os, sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(REPO, "manifest.json")
OUT = os.path.join(REPO, "docs", "prompt-skill-map.md")


def render(data):
    skills = data["skills"]
    prompts = data["prompts"]
    skill_names = {(s["category"], s["name"]) for s in skills}
    prompt_names = {(p["category"], p["name"]) for p in prompts}
    all_keys = sorted(skill_names | prompt_names)

    lines = [
        "# Prompt ↔ Skill Map",
        "",
        "Generated by `tools/gen_crossmap.py` from `manifest.json` — do not edit by hand.",
        "",
        "Every leadership task is available as a **prompt** (paste-and-fill), a **skill** "
        "(agent acts), or both. ✅ = present, — = not present.",
        "",
        "| Category | Task | Prompt | Skill |",
        "|----------|------|--------|-------|",
    ]
    for cat, name in all_keys:
        has_prompt = "✅" if (cat, name) in prompt_names else "—"
        has_skill = "✅" if (cat, name) in skill_names else "—"
        lines.append(f"| {cat} | {name} | {has_prompt} | {has_skill} |")

    both = len(skill_names & prompt_names)
    only_skill = len(skill_names - prompt_names)
    only_prompt = len(prompt_names - skill_names)
    lines += [
        "",
        f"**Totals:** {both} as both · {only_prompt} prompt-only · {only_skill} skill-only.",
        "",
    ]
    return "\n".join(lines)


def main():
    with open(MANIFEST, encoding="utf-8") as f:
        data = json.load(f)
    content = render(data)
    if "--check" in sys.argv:
        current = ""
        if os.path.isfile(OUT):
            with open(OUT, encoding="utf-8") as f:
                current = f.read()
        if current != content:
            print("FAIL: docs/prompt-skill-map.md is stale — run: python tools/gen_crossmap.py")
            sys.exit(1)
        print("PASS: prompt-skill-map.md up to date")
        sys.exit(0)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Wrote {os.path.relpath(OUT, REPO)}")


if __name__ == "__main__":
    main()
